name: slack_notification
on:
  push:
    branches:
      - master

jobs:
  notification:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run deployment process
        run: exit 0

      - name: Notify deployment
        uses: 8398a7/action-slack@v3.8.0
        with:
          status: ${{ job.status }}
        env:
          GITHUB_TOKEN: ${{ secrets.DOCKER_TEMP }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_SAITAMAUNIV_SAKURAIRIHITO }}
        if: always()